(function($){"use strict";jQuery(document).ready(function(){jQuery(window).on('load',function(){jQuery("#load").fadeOut();jQuery("#loading").delay(0).fadeOut("slow");jQuery('#back-to-top').fadeOut();jQuery(window).on("scroll",function(){if(jQuery(this).scrollTop()>250){jQuery('#back-to-top').fadeIn(1400);}else{jQuery('#back-to-top').fadeOut(400);}});jQuery('#top').on('click',function(){jQuery('top').tooltip('hide');jQuery('body,html').animate({scrollTop:0},800);return false;});jQuery(".navbar a").on("click",function(event){jQuery(".navbar-collapse").collapse('hide');});jQuery('.ad-title').on('click',function(e){e.preventDefault();var $this=jQuery(this);if($this.next().hasClass('show')){$this.next().removeClass('show');$this.next().slideUp(350);$this.parent().removeClass('ad-active');}else{$this.parent().addClass('ad-active');jQuery('.ad-title').not(this).parent().removeClass('ad-active');$this.parent().parent().find('div .ad-details').removeClass('show');$this.parent().parent().find('div .ad-details').slideUp(350);$this.next().toggleClass('show');$this.next().slideToggle(350);}});if(jQuery(window).scrollTop()>80){jQuery('#main-header').addClass('menu-sticky');}else{jQuery('#main-header').removeClass('menu-sticky');}
jQuery(window).on('scroll',function(){if(jQuery(this).scrollTop()>80){jQuery('#main-header').addClass('menu-sticky');}else{jQuery('#main-header').removeClass('menu-sticky');}});jQuery(window).on("scroll",onScroll);jQuery('header #top-menu a[href^="#"]').on('click',function(e){jQuery('#main-header').addClass('menu-sticky');jQuery(window).off("scroll");jQuery('header #top-menu a').each(function(){jQuery(this).parent().removeClass('current-menu-item');})
jQuery(this).parent().addClass('current-menu-item');var target=this.hash;var nav=jQuery(target);if(nav.length){var contentNav=nav.offset().top;jQuery('html, body').stop().animate({'scrollTop':contentNav},500,'swing',function(){window.location.hash=target;jQuery(window).on("scroll",onScroll);});}});function onScroll(event){var scrollPos=jQuery(window).scrollTop()+80;jQuery('header #top-menu a[href^="#"]').each(function(){if(jQuery(this).attr("href").indexOf('https://')==-1){var refElement=jQuery(jQuery(this).attr("href"));}else{var refElement=jQuery(this);}
if(jQuery(this).attr("href").indexOf('https://')==-1){if(!refElement.length)return;if(refElement.position().top<=scrollPos){jQuery(document).find('.menu-item').removeClass("current-menu-item current-menu-parent");jQuery(this).parent().addClass("current-menu-item");}else{jQuery(this).parent().removeClass("current-menu-item");}}});}
jQuery('#myTab li a').on('click',function(){jQuery('#myTab li a').attr('aria-selected',false);jQuery(this).attr('aria-selected',true);});jQuery(window).on('scroll',function(e){var nav=jQuery('#features');if(nav.length){var contentNav=nav.offset().top-250;if(jQuery(this).scrollTop()>=(contentNav)){e.preventDefault();jQuery('#features .row #myTab li a').removeClass('active');jQuery('#features .row #myTab li').children('a[aria-selected=true]').addClass('active');}}});var mySkrollr=skrollr.init({forceHeight:false,easings:{easeOutBack:function(p,s){s=1.70158;p=p-1;return(p*p*((s+1)*p+s)+1);}},mobileCheck:function(){return false;}});jQuery('.popup-gallery').magnificPopup({delegate:'a.popup-img',tLoading:'Loading image #%curr%...',type:'image',mainClass:'mfp-img-mobile',gallery:{navigateByImgClick:true,enabled:true,preload:[0,1]},image:{tError:'<a href="%url%">The image #%curr%</a> could not be loaded.'}});jQuery('.popup-youtube, .popup-vimeo, .popup-gmaps').magnificPopup({type:'iframe',disableOn:700,mainClass:'mfp-fade',preloader:false,removalDelay:160,fixedContentPos:false});jQuery('#countdown').countdown({date:'10/01/2019 23:59:59',day:'Day',days:'Days'});jQuery('.iq-progress-bar > span').each(function(){var $this=jQuery(this);var width=jQuery(this).data('percent');$this.css({'transition':'width 2s'});setTimeout(function(){$this.appear(function(){$this.css('width',width+'%');});},500);});jQuery('.iq-widget-menu > ul > li > a').on('click',function(){var checkElement=jQuery(this).next();jQuery('.iq-widget-menu li').removeClass('active');jQuery(this).closest('li').addClass('active');if((checkElement.is('ul'))&&(checkElement.is(':visible'))){jQuery(this).closest('li').removeClass('active');checkElement.slideUp('normal');}
if((checkElement.is('ul'))&&(!checkElement.is(':visible'))){jQuery('.iq-widget-menu ul ul:visible').slideUp('normal');checkElement.slideDown('normal');}
if(jQuery(this).closest('li').find('ul').children().length===0){return true;}else{return false;}});jQuery('.timer').countTo();jQuery('.owl-carousel').each(function(){var $carousel=$(this);$carousel.owlCarousel({items:$carousel.data("items"),loop:$carousel.data("loop"),margin:$carousel.data("margin"),nav:$carousel.data("nav"),dots:$carousel.data("dots"),autoplay:$carousel.data("autoplay"),autoplayTimeout:$carousel.data("autoplay-timeout"),navText:["<i class='fa fa-angle-left fa-2x'></i>","<i class='fa fa-angle-right fa-2x'></i>"],responsiveClass:true,responsive:{0:{items:$carousel.data("items-mobile-sm")},480:{items:$carousel.data("items-mobile")},786:{items:$carousel.data("items-tab")},1023:{items:$carousel.data("items-laptop")},1199:{items:$carousel.data("items")}}});});var slide=jQuery('.slider-single');var slideTotal=slide.length-1;var slideCurrent=-1;function slideInitial(){slide.addClass('proactivede');setTimeout(function(){slideRight();},500);}
function slideRight(){if(slideCurrent<slideTotal){slideCurrent++;}else{slideCurrent=0;}
if(slideCurrent>0){var preactiveSlide=slide.eq(slideCurrent-1);}else{var preactiveSlide=slide.eq(slideTotal);}
var activeSlide=slide.eq(slideCurrent);if(slideCurrent<slideTotal){var proactiveSlide=slide.eq(slideCurrent+1);}else{var proactiveSlide=slide.eq(0);}
slide.each(function(){var thisSlide=jQuery(this);if(thisSlide.hasClass('preactivede')){thisSlide.removeClass('preactivede preactive active proactive').addClass('proactivede');}
if(thisSlide.hasClass('preactive')){thisSlide.removeClass('preactive active proactive proactivede').addClass('preactivede');}});preactiveSlide.removeClass('preactivede active proactive proactivede').addClass('preactive');activeSlide.removeClass('preactivede preactive proactive proactivede').addClass('active');proactiveSlide.removeClass('preactivede preactive active proactivede').addClass('proactive');}
function slideLeft(){if(slideCurrent>0){slideCurrent--;}else{slideCurrent=slideTotal;}
if(slideCurrent<slideTotal){var proactiveSlide=slide.eq(slideCurrent+1);}else{var proactiveSlide=slide.eq(0);}
var activeSlide=slide.eq(slideCurrent);if(slideCurrent>0){var preactiveSlide=slide.eq(slideCurrent-1);}else{var preactiveSlide=slide.eq(slideTotal);}
slide.each(function(){var thisSlide=jQuery(this);if(thisSlide.hasClass('proactivede')){thisSlide.removeClass('preactive active proactive proactivede').addClass('preactivede');}
if(thisSlide.hasClass('proactive')){thisSlide.removeClass('preactivede preactive active proactive').addClass('proactivede');}});preactiveSlide.removeClass('preactivede active proactive proactivede').addClass('preactive');activeSlide.removeClass('preactivede preactive proactive proactivede').addClass('active');proactiveSlide.removeClass('preactivede preactive active proactivede').addClass('proactive');}
var left=jQuery('.slider-left');var right=jQuery('.slider-right');left.on('click',function(){slideLeft();});right.on('click',function(){slideRight();});slideInitial();if(!jQuery("body").hasClass("home")){if(jQuery("body").hasClass("page-id-346")){$href=jQuery('a.navbar-brand').attr('href')+"home-2/";}
else if(jQuery("body").hasClass("page-id-356")){$href=jQuery('a.navbar-brand').attr('href')+"home-3/";}
else if(jQuery("body").hasClass("page-id-737")){$href=jQuery('a.navbar-brand').attr('href')+"home-4/";}
else if(jQuery("body").hasClass("page-id-739")){$href=jQuery('a.navbar-brand').attr('href')+"home-5/";}
else if(jQuery("body").hasClass("page-id-744")){$href=jQuery('a.navbar-brand').attr('href')+"home-6/";}
else if(jQuery("body").hasClass("page-id-749")){$href=jQuery('a.navbar-brand').attr('href')+"home-7/";}
else if(jQuery("body").hasClass("page-id-751")){$href=jQuery('a.navbar-brand').attr('href')+"home-8/";}
else if(jQuery("body").hasClass("page-id-753")){$href=jQuery('a.navbar-brand').attr('href')+"home-9/";}
else if(jQuery("body").hasClass("page-id-764")){$href=jQuery('a.navbar-brand').attr('href')+"home-10/";}
else if(jQuery("body").hasClass("page-id-766")){$href=jQuery('a.navbar-brand').attr('href')+"home-11/";}
else if(jQuery("body").hasClass("page-id-774")){$href=jQuery('a.navbar-brand').attr('href')+"home-12/";}
else if(jQuery("body").hasClass("page-id-775")){$href=jQuery('a.navbar-brand').attr('href')+"home-13/";}
else if(jQuery("body").hasClass("page-id-779")){$href=jQuery('a.navbar-brand').attr('href')+"home-14/";}
else if(jQuery("body").hasClass("page-id-781")){$href=jQuery('a.navbar-brand').attr('href')+"home-15/";}
else if(jQuery("body").hasClass("page-id-783")){$href=jQuery('a.navbar-brand').attr('href')+"home-16/";}
else if(jQuery("body").hasClass("page-id-788")){$href=jQuery('a.navbar-brand').attr('href')+"home-17/";}
else if(jQuery("body").hasClass("page-id-790")){$href=jQuery('a.navbar-brand').attr('href')+"home-18/";}
else{var $href=jQuery('a.navbar-brand').attr('href');}
jQuery('.navbar ul li a, .widget ul.menu li a').each(function(){var $ahref=jQuery(this).attr('href');if(!$ahref){return;}
if($ahref.indexOf("#")!=-1){var $finalurl=$href+$ahref;jQuery(this).attr("href",$finalurl)}});}
if(jQuery("body").hasClass("home")){jQuery('.menu_first').addClass('show');jQuery('.menu_second').removeClass('show');}else{jQuery('.menu_second').addClass('show');jQuery('.menu_first').removeClass('show');}
jQuery.each(jQuery('.iq-background-overlay'),function(){var $i;var $p;$i=jQuery(this).attr('id');$i='#'+$i;$p=jQuery($i).parent().parent().parent().addClass($i);jQuery($i).parent().parent().parent().addClass('section_overlay');jQuery($i).insertBefore($p);});jQuery.each(jQuery('.layer_wrap'),function(){var $i;var $p;$i=jQuery(this).attr('id');$i='#'+$i;$p=jQuery($i).parent().parent().parent().addClass($i);jQuery($i).parent().parent().parent().addClass('section_overlay');jQuery($i).insertBefore($p);});jQuery('ul.page-numbers').removeClass('page-numbers').addClass('pagination justify-content-center');jQuery('.page-id-356, .page-id-346, .page-id-737, .page-id-739, .page-id-744, .page-id-751, .page-id-753, .page-id-764, .page-id-766, .page-id-788, .page-id-790, .page-id-774, .page-id-775, .page-id-779, .page-id-781, .page-id-783').addClass('home');jQuery('.page-id-749').addClass('home');if(jQuery('body').hasClass('blog')){jQuery('#blog.iq-page-blog').addClass('blog-single-style');}
jQuery('.sub-menu').css('display','none');jQuery('.sub-menu').prev().addClass('isubmenu');jQuery(".sub-menu").before('<i class="fa fa-angle-down toggledrop" aria-hidden="true"></i>');jQuery('.widget .fa.fa-angle-down, #main .fa.fa-angle-down').on('click',function(){jQuery(this).next('.children, .sub-menu').slideToggle();});jQuery("#top-menu .menu-item .toggledrop").off("click");if(jQuery(window).width()<992){jQuery('#top-menu .menu-item .toggledrop').on('click',function(e){e.preventDefault();jQuery(this).next('.children, .sub-menu').slideToggle();});}});jQuery(window).on('resize',function(){jQuery('.widget .fa.fa-angle-down, #main .fa.fa-angle-down').on('click',function(){jQuery(this).next('.children, .sub-menu').slideToggle();});jQuery("#top-menu .menu-item .toggledrop").off("click");if(jQuery(window).width()<992){jQuery('#top-menu .menu-item .toggledrop').on('click',function(e){e.preventDefault();jQuery(this).next('.children, .sub-menu').slideToggle();});}});});})(jQuery);